// flow-typed signature: fe9eb6797c72a3884bad4dd7215c8235
// flow-typed version: <<STUB>>/eslint-codeframe-formatter_v^1.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-codeframe-formatter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-codeframe-formatter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-codeframe-formatter/index' {
  declare module.exports: $Exports<'eslint-codeframe-formatter'>;
}
declare module 'eslint-codeframe-formatter/index.js' {
  declare module.exports: $Exports<'eslint-codeframe-formatter'>;
}
